### ISSUE TITLE
Excel Detection of Header start has wrong offset

### ISSUE THREAD

**Issue by rrkommer** [micromata/Merlin#61]
With following Excel (2003 format)
![grafik](https://user-images.githubusercontent.com/3179124/51533152-54269400-1e42-11e9-9be2-b577e7dfc1a7.png)
and a validator:
sheet.registerColumn("E-Mail", new ExcelColumnPatternValidator().setEMailPattern())
the column index for the E-Mail Column is wrong (0 instead of 1). 

Tested with Merlin 1.0.1

**Comment by kreinhard** [comment]
Calling of ExcelSheet.findAndReadHeadRow() is now done automatically.
As I know, you fixed this already in your branch.

**Comment by kreinhard** [comment]
Disregard, there was really a bug in ExcelSheet. In rows empty cells at the begin of a row might be ignored. Replaced the counter by cell.columnIndex.
